[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
fnv = "1.0.7"
impl_ops = "0.1.1"
itertools = "0.12"
nom = "7.1.3"
paste = "1.0"
tuple-map = "0.4.0"

[profile.bench]
lto = true
